<?php

namespace Socialgeo\EventBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class WijkController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Socialgeo\EventBundle\Controller\WijkController();
        return $instance;
    }
}
